# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: nikeee/docfx-action@v1.0.0
        name: Build docfx
        with:
         args: docs/docfx.json
         
      - name: Generating AsyncAPI documentation
        uses: asyncapi/github-action-for-generator@v1
        with:
          template: '@asyncapi/html-template@0.15.4'  #In case of template from npm, because of @ it must be in quotes
          filepath: docs/api/cc/my-asyncapi.yml
          parameters: baseHref=/test-experiment/ sidebarOrganization=byTags #space separated list of key/values
          output: docs/api/cc

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/_site # The folder the action should deploy.
